Repository 2024FALL-SWPP/team-project-for-2024-fall-swpp-team-12, pull requests merged in 2024-12, with the labels that each got.

#160 [D-021] Fixed 1/4 Turn Animation
  Chronus/Assets/Art/3D Models/Character/MainCharacter.fbx
Labels: bug, design

#161 [F-039-1] 튜토리얼 레벨 조작키 위치 수정
  Chronus/Assets/Scenes/LevelBaseScene.unity
Labels: design, feature

#168 [L-004] Added One More Tile that the Lever Controls
  Chronus/Assets/Scenes/L-004/L-004-2.unity
Labels: design
